### ISSUE TITLE
[libdrm] files installed by libdrm in x86_64 and riscv64 are not the same.

### ISSUE THREAD

**Issue by FantasqueX** [felixonmars/archriscv-packages#1326]
After checking by using `pacman -Ql libdrm`, I find that files installed by libdrm in x86_64 and riscv64 are not the same. Specifically, libdrm /usr/lib/pkgconfig/libdrm_intel.pc is missing in riscv64. Because there is no patch for libdrm, I believe there are some mistakes which should be investigated.

What's more, this issue blocks mesa-amber.

**Comment by felixonmars** [comment]
I don't think libdrm_intel is relevant for riscv64 as there won't be Intel GPU on riscv64.

**Comment by r-value** [comment]
FYI → #417

**Comment by FantasqueX** [comment]
We shouldn't add intel dri drivers because we won't receive any support from intel.
