### ISSUE TITLE
python-setuptool have different behavior between arch rv and arch x64

### ISSUE THREAD

**Issue by Avimitin** [felixonmars/archriscv-packages#1732]
Packages that built with python-setuptools will have different build library path between Arch RISC-V and Arch x86_64.

The reason of this issue is that python-setuptools [change the implementation](https://github.com/pypa/setuptools/commit/1c23f5e1e4b18b50081cbabb2dea22bf345f5894) of build library path generation in 62.1(Latest version in Arch x86_64). However we are still using the 61.3.1 version with the old implementation.

The build library path can be defined by build option `build-lib`. If user doesn't modify it manually, this option is default assigned to value of the base build directory(`build/`) plus a platform specfier.
The platform specifier is consist with current OS name and a tag. And the value of the tag is the key point of the whole issue:

* In 61.3.1, python-setuptools use `sys.version_info[:2]` as tag value, which should be `3` and `10` in our riscv machine.

```python
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=10, micro=7, releaselevel='final', serial=0)
>>> sys.version_info[:2]
(3, 10)
```

* However in 62.3.4, python-setuptools use `sys.implementation.cache_tag` as tag value, so we will get the below output in x86_64

```python
>>> import sys
>>> sys.implementation.cache_tag
'cpython-310'
```

So that's why there is no "cpython" suffix when we build this package on Arch RV. Currently I suggest that we can add a patch to trim the path and remove those patch after we have newer version of the python-setuptools.

> Reference:
> * 61.3.1(Arch RV Latest) implementation of the build directory specifier: https://github.com/pypa/setuptools/blob/v61.3.1/setuptools/_distutils/command/build.py#L84
> * 62.3.4(Arch x86_64 Latest) implementation of the build directory specifier: https://github.com/pypa/setuptools/blob/v62.3.4/setuptools/_distutils/command/build.py#L85

**Comment by felixonmars** [comment]
Thanks. The `riscv64` setuptools has been updated to the same version as `x86_64`. This should have now been fixed.
