### ISSUE TITLE
Usage and contribution

### ISSUE THREAD

**Issue by mjdr** [felixonmars/archriscv-packages#2]
Hi,
I want to see arch linux on riscv too.
How I can setup build environment and contribute?
I tried to setup env with docker and qemu-static

**Comment by felixonmars** [comment]
You can download a image from https://archriscv.felixc.at/images/ or optionally pacstrap from this mirror with a modified Architecture. Currently most documentation is still missing :(

**Comment by mjdr** [comment]
How exactly I can build arch's official packages and create my own repo?
I didn't find any documentation on archwiki

**Comment by felixonmars** [comment]
You can refer to the regular instructions for creating a repo. For building official packages, please use devtools. We'll add more documentation later.

**Comment by mjdr** [comment]
Ok, thanks

**Comment by StarterX4** [comment]
> You can download a image from https://archriscv.felixc.at/images/ or optionally pacstrap from this mirror (https://archriscv.felixc.at/repo/) with a modified Architecture. Currently most documentation is still missing :(

Hey, what's the default root password in 2021 image? It looks like there is some [in /etc/shadow].

**Comment by Xeonacid** [comment]
> Hey, what's the default root password in 2021 image? It looks like there is some [in /etc/shadow].

@StarterX4 It's `sifive` :->
