### ISSUE TITLE
pyside2 needs to be rebuilt

### ISSUE THREAD

**Issue by Avimitin** [felixonmars/archriscv-packages#2075]
Package pyside2 is missing file `typesystem_webenginecore.xml`. The missing file cause another package `falkon` fail to build.

* x86_64

```bash
$ pacman -Fl pyside2 | grep 'typesystem_webenginecore.xml'
pyside2 usr/share/PySide2/typesystems/typesystem_webenginecore.xml
```

* riscv64

```bash
$ pacman -Fl pyside2 | grep 'typesystem_webenginecore.xml'
...empty output...
```

**Comment by felixonmars** [comment]
Fixed in 5.15.7-1.1

checkpkg output:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/1006477/209835229-ce3abd64-b282-4e8d-a5c6-d835f7e6eb3e.png">
