### ISSUE TITLE
gst-plugins-bad can't be installed because pipewire required libcamera version 0.0.3-64

### ISSUE THREAD

**Issue by CarlosRFS** [felixonmars/archriscv-packages#2168]
I was making a new install for my allwinnerD1 and i need gst-plugins-bad(who has v4l2 stateless codecs plugins) and pipewire is a dependency of him. But the install can't progress cause pacman couldn't solve  some dependencies of him like below:
```
warning: cannot resolve "libcamera-base.so=0.0.3-64", a dependency of "pipewire"
warning: cannot resolve "libcamera.so=0.0.3-64", a dependency of "pipewire"
warning: cannot resolve "libpipewire-0.3.so=0-64", a dependency of "fluidsynth"
warning: cannot resolve "fluidsynth", a dependency of "gst-plugins-bad"
:: The following package cannot be upgraded due to unresolvable dependencies:
      gst-plugins-bad

:: Do you want to skip the above package for this upgrade? [y/N] 

```

The problem is that libcamera its already version 0.0.4-1 on repo and pipewire is requiring exacly the version  0.0.3-64.
Probably add a '>' on the PKGBUILD to allow newer versions of libcamera would solve, but you have some reason for they ask only a specific version? 

**EDIT: use -d on pacman to ignore dependency check could help who had the same problem. But its not recommended**

**Comment by felixonmars** [comment]
sodepends are expected to require exactly the soversion as part of the design (and functionality), so this error actually indicated a problem in our repository. I just tried again and it seems to be fixed already.

As we don't have a proper staging repository structure right now, problems like this are still expected from time to time but should always be fixed very soon.

**Comment by Xeonacid** [comment]
Fixed. Closing.
