### ISSUE TITLE
bootstrapping aarch64-linux-gnu-gcc and aarch64-linux-gnu-glibc

### ISSUE THREAD

**Issue by bastianplettner** [felixonmars/archriscv-packages#2203]
I'm not quite sure if this is the right approach, but I tried bootstrapping `aarch64-linux-gnu-gcc` and `aarch64-linux-gnu-glibc`.
Because I don't have any experience with bootstrapping gcc whatsoever, I used a modified version of [aarch64-gcc-bootstrap](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aarch64-gcc-bootstrap) from the AUR, following the procedure outlined in the PKGBUILD.

Either way, I now have natively compiled packages for `aarch64-linux-gnu-gcc` and `aarch64-linux-gnu-glibc`, which could be used for compiling the 'official' versions of those packages. Both  `aarch64-linux-gnu-gcc` and `aarch64-linux-gnu-glibc` built fine without any patches to their PKGBUILDs.
I am not sure what the right procedure for bootstrapping these packages is here, or if I should share my binaries for this purpose?

**Comment by Xeonacid** [comment]
You may create two packages named `aarch64-linux-gnu-gcc-bootstrap` and `aarch64-linux-gnu-glibc-bootstrap`, like what we do in [gcc-d-bootstrap](https://github.com/felixonmars/archriscv-packages/blob/master/gcc-d-bootstrap/PKGBUILD). :)

**Comment by bastianplettner** [comment]
Alright, I'll take a look at that.
Thanks
