### ISSUE TITLE
很抱歉这样打扰您：您打包的 fcitx5-rime 和 librime 有问题

### ISSUE THREAD

**Issue by yanhuacuo** [felixonmars/archriscv-packages#2273]
从最早三年前：https://www.v2ex.com/t/726643

到两年前：https://github.com/fcitx/fcitx5-rime/issues/16

再到如今：https://github.com/fcitx/fcitx5-rime/issues/53

您打包的 fcitx5-rime 和 librime 一直被 Arch 收录，并扩散到各种 Arch 衍生版上。

但是：librime-lua 从来没有正常过，早期 fcitx5-rime 在源码里写了手动加载途径，还可以手动加载，现在自动识别，致使再无可行之法，只能重头编译整个项目。

不论是独立编译 librime ，还是编译 fcitx5-rime，请将 [librime-lua](https://github.com/hchunhui/librime-lua) 按照它的 [librime-lua/wiki](https://github.com/hchunhui/librime-lua/wiki) 放到 `librime/plugins` 下面，否则 `librime` 引擎是一定不能正确识别「lua」插件的。

冒昧打扰，见谅。

**Comment by Avimitin** [comment]
Consider sending this issue to https://bugs.archlinux.org. This problem is not related to the RISC-V package.

**Comment by Avimitin** [comment]
Consider sending this issue to Manjaro upstream. Manjaro is NOT Arch Linux. This problem is also unrelated to this repository.

**Comment by XieJiSS** [comment]
The scope of this repo is currently limited to porting packages onto the RISC-V platform. Problem / bug of any package that is not RISC-V specific should be sent to the Arch Linux bug tracker instead, thanks!

**Comment by yanhuacuo** [comment]
> The scope of this repo is currently limited to porting packages onto the RISC-V platform. Problem / bug of any package that is not RISC-V specific should be sent to the Arch Linux bug tracker instead, thanks!

Sorry，I just want to tell the gay →「Felix Yan」→「Please read the wiki correctly」

**Comment by CoelacanthusHex** [comment]
> > The scope of this repo is currently limited to porting packages onto the RISC-V platform. Problem / bug of any package that is not RISC-V specific should be sent to the Arch Linux bug tracker instead, thanks!
> 
> Sorry，I just want to tell the gay →「**Felix Yan**」→「**Please read the wiki correctly**」

Just mail to Felix Yan or talk to them in distro discussion group. Don't spam an unrelated project.

**Comment by Avimitin** [comment]
> Sorry，I just want to tell the gay →「**Felix Yan**」→「**Please read the wiki correctly**」

Can you confirm that this issue is coming from incorrect packaging? Bug report require detailed behavior descriptions. We don't have any information to prove that this bug is indeed a packaging issue. So it is rude to ask the developer to "do something correctly" if you don't have relevant evidence.

**Comment by felixonmars** [comment]
> > The scope of this repo is currently limited to porting packages onto the RISC-V platform. Problem / bug of any package that is not RISC-V specific should be sent to the Arch Linux bug tracker instead, thanks!
> 
> Sorry，I just want to tell the gay →「**Felix Yan**」→「**Please read the [wiki](https://github.com/hchunhui/librime-lua/wiki) correctly**」

Well, I dunno what is going on here. What did I read wrong?

librime-lua is correctly compiled and installed in the librime package as instructed:

https://github.com/archlinux/svntogit-community/blob/packages/librime/trunk/PKGBUILD#L31
