### ISSUE TITLE
PyQt5 need rebuild

### ISSUE THREAD

**Issue by saeziae** [felixonmars/archriscv-packages#2300]
```python
>> from PyQt5.Qt import QValidator
AttributeError: module 'PyQt5.Qt' has no attribute 'QValidator'
```
A rebuild fixes this.

**Comment by felixonmars** [comment]
Rebuilt as python-pyqt5-5.15.9-1, please try again.

**Comment by saeziae** [comment]
`python-pyqt5-5.15.9-1.1` works correctly now. Then I think `gnuradio` would pass `check()` now.
