### ISSUE TITLE
python-nltk 和 nltk-data 打包

### ISSUE THREAD

**Issue by kxxt** [felixonmars/archriscv-packages#2427]
`python-nltk` checkdepends `nltk-data`, `nltk-data` makedepends  `python-nltk`.

# 方案

1. 先使用 `--nocheck` 选项构建 `python-nltk`
2. 利用1. 打出的包构建 `nltk-data` 
    - 这个包可能 `package()` 的时间有亿点点长 ,  ~~可以先喝几百杯茶~~)
4. 然后即可利用 2. 打出的包正常构建 `python-nltk` (其实 `check()` 目前被上游注释掉了, 这一步可以跳过

# 手动 check 方法

- `python -c "import nltk;nltk.download('omw-1.4')"`
- `pacman install python-pytest-mock`
- `pytest`

只有一个测试过不去, 因为这个测试依赖 `matplotlib`.  (注意, 上游并没有把 matplotlib 加进 checkdepends 里)

目前仓库里的 `matplotlib` 还是 python 3.9 的. 我手动安装 `matplotlib` 之后该测试可以通过:

```bash
git clone https://github.com/matplotlib/matplotlib
cd matplotlib
cat << EOF > mplsetup.cfg
[libs]
system_freetype = true
system_qhull = true
EOF
sudo pip install .
```

**Comment by felixonmars** [comment]
谢谢，已经 bootstrap 成功 :)
