### ISSUE TITLE
Add CI test support for bazaar source

### ISSUE THREAD

**Issue by a1ca7raz** [felixonmars/archriscv-packages#2501]
I successfully fixed [libappindicator](https://github.com/felixonmars/archriscv-packages/pull/2500). This package fetches source code from launchpad via breezy.
But it [failed](https://github.com/felixonmars/archriscv-packages/actions/runs/4670769644/jobs/8270910927) to pass the CI test. The test does not support breezy and fetching from launchpad via breezy.
I have fixed the test script and CI workflow. Is it possible to merge the pr?

**Comment by a1ca7raz** [comment]
I reported the missing dep to archlinux. libappindicator should be ok soon.
https://bugs.archlinux.org/task/78176
But breezy is still missing in make dependencies of CI test.

**Comment by Xeonacid** [comment]
> But breezy is still missing in make dependencies of CI test.

You may submit a PR to install `devtools` as mentioned before.
