### ISSUE TITLE
Enable Allwinner D1 support in kernel

### ISSUE THREAD

**Issue by sehraf** [felixonmars/archriscv-packages#2566]
With Linux 6.3 the Allwinner D1 SoC is supported and thus needs to be enabled in the kernel configuration.

Notes:
 - For reference: https://github.com/torvalds/linux/commit/eb20e7cb91ba3e5dbd94b6bfc8b9609bd5fd5770
 - Based on telegram group: HDMI is not supported yet.

**Comment by CoelacanthusHex** [comment]
It will be enabled after 6.3 released into Arch Linux stable repo.

**Comment by sehraf** [comment]
any progress?

**Comment by CoelacanthusHex** [comment]
> any progress?

Blocked by some boot failure on Unmatched, I'm trying to fix it.
