### ISSUE TITLE
error: failed to download signature of package 'duplicity-1.2.3-2-riscv64.pkg.tar.zst'!

### ISSUE THREAD

**Issue by philmmanjaro** [felixonmars/archriscv-packages#2632]
During syncing we get the following error: `error: failed to download signature of package 'duplicity-1.2.3-2-riscv64.pkg.tar.zst'!
`

**Comment by felixonmars** [comment]
Should have been fixed now. I'll be adding some integrity checks to avoid these issues in the future.
