### ISSUE TITLE
error: failed to download signature of package 'ukui-control-center-3.0.4-5-riscv64.pkg.tar.zst'!

### ISSUE THREAD

**Issue by philmmanjaro** [felixonmars/archriscv-packages#2640]
During sync we had the following issue: `error: failed to download signature of package 'ukui-control-center-3.0.4-5-riscv64.pkg.tar.zst'!`

**Comment by felixonmars** [comment]
Fixed now.

Check is also added at https://github.com/felixonmars/archlinux-futils/commit/fe3f2a9ccc964305a01e61a3d98a87629f5f94f5
<img width="510" alt="image" src="https://github.com/felixonmars/archriscv-packages/assets/1006477/a8d05e7a-f899-4e82-a1f7-b764802a2160">
