### ISSUE TITLE
freeradius libssl version mismatch

### ISSUE THREAD

**Issue by armdn** [felixonmars/archriscv-packages#3748]
Again this error appears. As it was there: [3728](https://github.com/felixonmars/archriscv-packages/issues/3728)

`libssl version mismatch.  built: 30200010 linked: 30300000`

**Comment by armdn** [comment]
Ping?

**Comment by felixonmars** [comment]
I was waiting for its dependency `yubico-c`/`yubico-c-client` to be fixed first, but turns out no one had the time. freeradius 3.2.4-1 has been pushed with the rebuild. Sorry for the delay!
