### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by gmankab** [felixonmars/archriscv-packages#3772]
hello

now if you have risc-v computer you can't run x86 docker image on it

so, can you please provide a docker image

it would be very nice to use arch in docker, podman, toolbox, and distrobox on risc-v

**Comment by Xeroxxx** [comment]
If you check on https://riscv.mirror.pkgbuild.com/ there is a link pointing to the docker repository building daily riscv images for arch by me.

https://hub.docker.com/r/riscfive/archlinux

**Comment by 197788** [comment]
Thanks.

Jun 16, 2024 04:46:17 ツ ***@***.***>:

**Comment by gmankab** [comment]
thank you

**Comment by Xeroxxx** [comment]
If there are any issues with the images let me know.

I agreed with felix on creating issues over here. I'll check form time to time, otherwise just reference me.

**Comment by gmankab** [comment]
i don't have any risc-v devices for now to test it, but i am planning to get one in the future
