### ISSUE TITLE
Tweak Rust package guidelines

### ISSUE THREAD

**Issue by alerque** [felixonmars/archriscv-packages#670]
I don't have any RISC boards, but poking around in here one thing that seems to need patching a lot is something I put in the Rust packaging guidelines.

https://github.com/felixonmars/archriscv-packages/blob/82d8d619e862478a076ae657069c9caf2f1caed4/onefetch/riscv64.patch

This platform limited fetch can mean a *huge* savings in downloads when building packages (in some cases from hundreds of MB down to less than 10), so I am loath to drop it altogether.

Would it be helpful to modify the Rust recommendations like so:

```diff
- cargo fetch --target "$CARCH-unknown-linux-gnu"
+ cargo fetch --target "$CHOST"
```

...or is the issue here that you are cross compiling and need to fetch far an architecture other than the host? If so is there a variable we could suggest people use to get the benefit of only downloading required sources while not making so much work patching downstream?

**Comment by r-value** [comment]
Unfortunately, neither `$CARCH` nor `$CHOST` provides correct triple for Rust. Rust needs something like `riscv64gc` but these variables are `riscv64`. So we'd like to just trim them off.

Ref: https://github.com/felixonmars/archriscv-packages/blob/master/devtools-riscv64/makepkg-riscv64.conf#L37

**Comment by alerque** [comment]
Bummer. Also a bummer [this](https://github.com/rust-lang/cargo/pull/6777#issuecomment-478574992) never got flushed out. Also a bummer my patch fixing the `cargo fetch --target` documentation that fixes the current contradiction in the man page was dropped. I need to resubmit that at least...

So *why* is Rust coming up with a different architecture name? Is this something it's impossible to normalize?

**Comment by XieJiSS** [comment]
Hi @alerque ,

https://github.com/laanwj/cc-rs/blob/4981b3cdf070c5f1f8ead508d5b56ea60ec657c2/src/lib.rs#L1431-L1441

I think that's partially because the compiler need to construct the `-march` argument to be passed to the underlying clang/llvm stuff from the `--target` argument. The `-march` uses the format similar to `rv64gc` / `rv64imac`.

**Comment by r-value** [comment]
> Is this something it's impossible to normalize?

I think that there can be two possible solutions. One is submitting patch to Rust and change the naming scheme to something like arch=`riscv64` and put extensions like G/C/V/K in `target-feature` just like what they did with x86 extensions. The other is to make a new environment variable like `$RSARCH` which contains `riscv64gc` on RISC-V and `x86_64` on x86.

**Comment by alerque** [comment]
Bah. So basically right now the only way to solve both my concern and eliminate the need for downstream patching would be something like this:

```bash
cargo fetch --locked --target "$(rustc -vV | awk '/^host:/ { print $2 }')"
```

Obviously that's a bit convoluted so I'm not recommending it yet, just trying to get my head around the problem here.

It seems to me the best course of action would be to actually fix `cargo` to work [as documented](https://doc.rust-lang.org/cargo/commands/cargo-fetch.html#fetch-options):

> --target triple
>    Fetch for the given architecture. The default is the host architecture.

As far as I can see there is no way to actually use this so called "default" in fetch, it only defaults to "all architectures" (which for some dependency chains is becoming pretty heavy!).

**Comment by piggynl** [comment]
Hi @alerque, I recreated your PR for cargo's doc change as rust-lang/cargo#10398 :eyes:

**Comment by Xeonacid** [comment]
Closing since there has been a working Rust package guidelines for a while. :)
